apiVersion: v1
kind: PersistenceVolume
metadata:
  name: mariadb-pv
  labels:
    local: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessMode:
   - ReadWriteOnce: 
  hostPath:
    path: "/mnt/data"
  PersistenceVolumeReclaimPolicy: Retain

---

