apiVersion: v1
kind: PersistenceVolume
metadata:
  name: mariadb-pv
  labels:
    local: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessMode:
   - ReadWriteOnce: 
  hostPath:
    path: "/mnt/data"
  PersistenceVolumeReclaimPolicy: Retain


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels: 
    app: kotlin-api-mariadb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi